#!/usr/bin/env python3
"""Render a canonical shared skill source for one target provider.

This reads canonical source, filters provider tags, flattens the target payload,
and prepends the generated provenance header. Installation and atomic rename
are intentionally left to the caller.
"""

from __future__ import annotations

import argparse
from datetime import datetime, timezone
import hashlib
from pathlib import Path
import sys
from typing import Sequence


_PUBLISHER_DIR = Path(__file__).resolve().parent
LIB_DIR = _PUBLISHER_DIR / "agentic-systems" / "lib"
if not LIB_DIR.is_dir():
    LIB_DIR = _PUBLISHER_DIR / "lib"
sys.path.insert(0, str(LIB_DIR))

from provider_blocks import ProviderBlockError, normalize_provider, render_for_provider  # noqa: E402


DEFAULT_SOURCE_VERSION = "content-addressed"


class PublishSkillError(ValueError):
    """Raised when a source cannot be rendered as a provider artifact."""


def sha256_hex(content: bytes) -> str:
    """Return the lowercase SHA-256 hex digest for bytes."""

    return hashlib.sha256(content).hexdigest()


def generated_at_now() -> str:
    """Return a deterministic-format UTC ISO-8601 timestamp for the header."""

    return datetime.now(timezone.utc).isoformat(timespec="seconds").replace("+00:00", "Z")


def build_provenance_header(
    *,
    source_path: str,
    source_version: str,
    source_sha256: str,
    target_provider: str,
    publisher_path: str,
    publisher_sha256: str,
    generated_at: str,
) -> str:
    """Build the seven-field generated provenance header."""

    provider = normalize_provider(target_provider).lower()
    return (
        "<!--\n"
        f"Generated from: {source_path}\n"
        f"Source version/hash: {source_version} sha256:{source_sha256}\n"
        f"Target provider: {provider}\n"
        f"Publisher: {publisher_path}\n"
        f"Publisher sha256: sha256:{publisher_sha256}\n"
        f"Generated at: {generated_at}\n"
        "Do not edit this file directly.\n"
        "-->\n\n"
    )


def render_published_skill_bytes(
    source_bytes: bytes,
    *,
    target_provider: str,
    source_path: str,
    publisher_path: str,
    publisher_bytes: bytes,
    generated_at: str | None = None,
    source_version: str = DEFAULT_SOURCE_VERSION,
) -> bytes:
    """Render source bytes into a generated provider artifact.

    The payload is encoded back to UTF-8 only after provider filtering. For
    tag-free UTF-8 source, the emitted payload bytes are identical to the input
    bytes; only the inserted provenance header differs. The header lands AFTER
    a leading YAML frontmatter block when one exists — provider skill loaders
    parse frontmatter only at byte 0, so a header-first artifact would break
    the provider-native interface the DIB guarantees.
    """

    try:
        source_text = source_bytes.decode("utf-8")
    except UnicodeDecodeError as exc:
        raise PublishSkillError("canonical source must be UTF-8") from exc

    target = normalize_provider(target_provider)
    payload = render_for_provider(source_text, target).encode("utf-8")
    header = build_provenance_header(
        source_path=source_path,
        source_version=source_version,
        source_sha256=sha256_hex(source_bytes),
        target_provider=target,
        publisher_path=publisher_path,
        publisher_sha256=sha256_hex(publisher_bytes),
        generated_at=generated_at or generated_at_now(),
    )
    return _insert_header(payload, header.encode("utf-8"))


def _insert_header(payload: bytes, header: bytes) -> bytes:
    """Insert the §5.4 header without breaking the artifact's native interface:
    a frontmatter-led payload keeps `---` at byte 0 and takes the header
    immediately after the closing `---`; anything else gets it prepended."""

    if payload.startswith(b"---\n"):
        end = payload.find(b"\n---\n", 4)
        if end != -1:
            cut = end + len(b"\n---\n")
            return payload[:cut] + header + payload[cut:]
    return header + payload


def render_published_skill_file(
    source_path: Path,
    *,
    target_provider: str,
    generated_at: str | None = None,
    source_version: str = DEFAULT_SOURCE_VERSION,
    publisher_path: Path | None = None,
) -> bytes:
    """Read a canonical source file and render it for one provider."""

    source = source_path.resolve()
    publisher = (publisher_path or Path(__file__)).resolve()
    return render_published_skill_bytes(
        source.read_bytes(),
        target_provider=target_provider,
        source_path=str(source),
        publisher_path=str(publisher),
        publisher_bytes=publisher.read_bytes(),
        generated_at=generated_at,
        source_version=source_version,
    )


def _parse_args(argv: Sequence[str] | None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Render a canonical provider-tagged SKILL.md for one provider."
    )
    parser.add_argument("source", type=Path, help="canonical source file to render")
    parser.add_argument(
        "--provider",
        required=True,
        help="target provider: claude, codex, or gemini",
    )
    parser.add_argument(
        "--source-version",
        default=DEFAULT_SOURCE_VERSION,
        help="version identifier to record beside the source hash",
    )
    parser.add_argument(
        "--generated-at",
        help="override the Generated at timestamp, primarily for tests",
    )
    return parser.parse_args(argv)


def _write_stdout(content: bytes) -> None:
    buffer = getattr(sys.stdout, "buffer", None)
    if buffer is None:
        sys.stdout.write(content.decode("utf-8"))
    else:
        buffer.write(content)


def main(argv: Sequence[str] | None = None) -> int:
    args = _parse_args(argv)
    try:
        rendered = render_published_skill_file(
            args.source,
            target_provider=args.provider,
            generated_at=args.generated_at,
            source_version=args.source_version,
        )
    except (OSError, ProviderBlockError, PublishSkillError) as exc:
        print(f"publish-skill.py: {exc}", file=sys.stderr)
        return 2
    _write_stdout(rendered)
    return 0


if __name__ == "__main__":
    sys.exit(main())
